// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFuTqQ9FR_sLjWAfQK78Wwo37F5mKUXE',
    appId: '1:475693822001:web:ace3d31598e6fb93d6e510',
    messagingSenderId: '475693822001',
    projectId: 'ibeamscanner',
    authDomain: 'ibeamscanner.firebaseapp.com',
    storageBucket: 'ibeamscanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlBXH61wtUdCEXEd8hHtly909HiY5mlM',
    appId: '1:475693822001:android:9ccc616a8bf7dc88d6e510',
    messagingSenderId: '475693822001',
    projectId: 'ibeamscanner',
    storageBucket: 'ibeamscanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd2BGcq2uuRyahs0K6syjn2c8wh0IaO_c',
    appId: '1:475693822001:ios:8a626a58013ec13ad6e510',
    messagingSenderId: '475693822001',
    projectId: 'ibeamscanner',
    storageBucket: 'ibeamscanner.firebasestorage.app',
    iosBundleId: 'com.example.ibeamScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd2BGcq2uuRyahs0K6syjn2c8wh0IaO_c',
    appId: '1:475693822001:ios:8a626a58013ec13ad6e510',
    messagingSenderId: '475693822001',
    projectId: 'ibeamscanner',
    storageBucket: 'ibeamscanner.firebasestorage.app',
    iosBundleId: 'com.example.ibeamScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBFuTqQ9FR_sLjWAfQK78Wwo37F5mKUXE',
    appId: '1:475693822001:web:967f5352b296f350d6e510',
    messagingSenderId: '475693822001',
    projectId: 'ibeamscanner',
    authDomain: 'ibeamscanner.firebaseapp.com',
    storageBucket: 'ibeamscanner.firebasestorage.app',
  );
}
